server:
  port: 8081
spring:
  application:
    name: seat-info-service
  data:
    mongodb:
      uri: mongodb://localhost:27017/seat-info-service
      database: seat-info
  elasticsearch:
      uris: http://localhost:9200